//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGMES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESUSERINFO
    {
        public long ID { get; set; }
        public string ENAME { get; set; }
        public string CNAME { get; set; }
        public string KEYVALUE { get; set; }
        public Nullable<short> ISENABLE { get; set; }
        public Nullable<long> DEPTID { get; set; }
        public Nullable<long> TREENO { get; set; }
        public string TIMETIRED { get; set; }
        public Nullable<short> PASSWD_PERIOD { get; set; }
        public string APPNAME { get; set; }
        public string PER_MONITORSTARTTIME { get; set; }
        public string TEM_MONITORSTARTTIME { get; set; }
        public string LAST_ERRORTIME { get; set; }
        public Nullable<int> PER_ERRORCOUNT { get; set; }
        public Nullable<int> TEM_ERRORCOUNT { get; set; }
    }
}
