//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGMES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTS0091
    {
        public string REC_ID { get; set; }
        public string MT_ID { get; set; }
        public string REC_CREATOR { get; set; }
        public string REC_CREATE_TIME { get; set; }
        public string REC_REVISOR { get; set; }
        public string REC_REVISE_TIME { get; set; }
        public string REC_DELETOR { get; set; }
        public string REC_DELETE_TIME { get; set; }
        public string DELETE_FLAG { get; set; }
        public string ARCHIVE_FLAG { get; set; }
        public string ARCHIVE_STAMP_NO { get; set; }
        public string REMARK { get; set; }
        public string CODE_CLASS { get; set; }
        public string CODE_NAME { get; set; }
        public short CODE_LEN { get; set; }
        public short CODE_ACT_LEN { get; set; }
        public string CODE_DESC_1_NAME { get; set; }
        public short CODE_DESC_1_LEN { get; set; }
        public string CODE_DESC_2_NAME { get; set; }
        public short CODE_DESC_2_LEN { get; set; }
        public string CODE_DESC_3_NAME { get; set; }
        public short CODE_DESC_3_LEN { get; set; }
        public string CODE_DESC_4_NAME { get; set; }
        public short CODE_DESC_4_LEN { get; set; }
        public string CODE_DESC_5_NAME { get; set; }
        public short CODE_DESC_5_LEN { get; set; }
        public string CODE_SOURCE { get; set; }
        public string CODE_AUTH { get; set; }
    }
}
