//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGMES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTS0092
    {
        public string REC_ID { get; set; }
        public string MT_ID { get; set; }
        public string REC_CREATOR { get; set; }
        public string REC_CREATE_TIME { get; set; }
        public string REC_REVISOR { get; set; }
        public string REC_REVISE_TIME { get; set; }
        public string REC_DELETOR { get; set; }
        public string REC_DELETE_TIME { get; set; }
        public string DELETE_FLAG { get; set; }
        public string ARCHIVE_FLAG { get; set; }
        public string ARCHIVE_STAMP_NO { get; set; }
        public string REMARK { get; set; }
        public string CODE_CLASS { get; set; }
        public string CODE { get; set; }
        public string CODE_DESC_1_CONTENT { get; set; }
        public string CODE_DESC_2_CONTENT { get; set; }
        public string CODE_DESC_3_CONTENT { get; set; }
        public string CODE_DESC_4_CONTENT { get; set; }
        public string CODE_DESC_5_CONTENT { get; set; }
    }
}
